### ISSUE TITLE
Id field on renderer initialisation

### ISSUE THREAD

**Issue by cristianvogel** [elemaudio/elementary#12]
I am developing a larger web site with Elementary basically in replacement of the global Audio object and WebAudio generic. 

In this context, I am finding it useful to instantiate multiple WebAudioRenderer ( alias WebRenderer ? ) 

What would be useful to make sure everything is routed and targeted correctly, is some introspection. 

I am proposing an optional  `id` field in the constructor, that at least gets returned at the `load()` event  but also maybe from a getter once loaded.

```
    this.port.postMessage(['load', {
      id,
      sampleRate,
      blockSize: 128,
      numInputChannels,
      numOutputChannels,
    }]);
  }
```
https://github.com/elemaudio/elementary/blob/05d8acd2b2c49228d1f8717da67015d5ceffeec2/js/packages/web-renderer/raw/WorkletProcessor.js#LL85C1-L91C4

**Comment by nick-thompson** [comment]
To make sure I understand this correctly, let me ask: because each WebRenderer instance is its own EventEmitter, don't you get events scoped to the correct instance by default?

```js
let core1 = new WebRenderer();
let core2 = new WebRenderer();

// Initialization and stuff omitted for brevity

core1.on(<anything>, (e) => {
  // You know this is coming from core1
});

core2.on(<anything>, (e) => {
  // You know this is coming from core2
});
```

For me that seems to provide everything we would need to distinguish which events come from which instance.

**Comment by cristianvogel** [comment]
Is this an acceptable way of adding such a custom property?
 `// extend renderer with custom id property
		Object.defineProperty(renderer, 'id', { value: id, writable: false });`

**Comment by nick-thompson** [comment]
Sure, if you like! JavaScript lets you do all kinds of stuff; you could just `renderer.id = id;` too.

**Comment by cristianvogel** [comment]
Yeah, I'm loving it. Its my favourite language after SmallTalk ;)
