### ISSUE TITLE
API for the Virtual File System

### ISSUE THREAD

**Issue by cristianvogel** [elemaudio/elementary#9]
Once more than a few assets get involved, things get murky. 

_Need_ a way to find out what is loaded, size, path etc 

Ideally, some methods to also garbage collect , clear out assets that are not being used, or replace them with others.

**Comment by nick-thompson** [comment]
> Once more than a few assets get involved, things get murky.

How so?

Generally I'm open to this idea for the web and offline renderer; I think at a minimum being able to ask the renderer what's in the map would be helpful. A simple GC step there would be doable too, with some care.

I want to be careful though around exactly what you might be able to query for, especially given that these renderers are basically just proxies to the wasm engine which holds the actual resources. To that end, would a `listVirtualFileSystem()` method be sufficient to address the murkiness you're seeing? Returning just a list of string names/paths that are currently present in the VFS?

**Comment by cristianvogel** [comment]
Murky meaning I cannot check which assets are in the VFS of which core when using more than one renderer, for example - or how to find, unload, duplicate or move. 

I guess just getting a list of keys , so I could reassign or null

**Comment by nick-thompson** [comment]
> Murky meaning I cannot check which assets are in the VFS

Would you mind elaborating on your use case here? Wouldn't you know which assets you've loaded into which renderer?

> unload, duplicate or move.

> I guess just getting a list of keys , so I could reassign or null could suffice

Right this is where we get into the risky territory I mentioned in "these renderers are basically just proxies to the wasm engine which holds the actual resources." I don't anticipate adding an API for _changing_ existing entries in the VFS; actually I have a task on my plate already to make the VFS more immutable. But if I understand this well enough, I think that we cover everything in an API that offers:

* adding to the VFS 
* listing what's in the VFS 
* Initiating a garbage collection pass (you won't exactly have control over what gets cleared)

How does that sound?

**Comment by cristianvogel** [comment]
Hey thanks Nick for thinking about this.I think your proposal is good. You explain the constraints here , and why it’s risky to make buffers mutable.  It is not supposed to be a fully fledged file system of course. —- On 14 May 2023, at 16.50, Nick Thompson ***@***.***> wrote:﻿

Murky meaning I cannot check which assets are in the VFS

Would you mind elaborating on your use case here? Wouldn't you know which assets you've loaded into which renderer?

unload, duplicate or move.


I guess just getting a list of keys , so I could reassign or null could suffice

Right this is where we get into the risky territory I mentioned in "these renderers are basically just proxies to the wasm engine which holds the actual resources." I don't anticipate adding an API for changing existing entries in the VFS; actually I have a task on my plate already to make the VFS more immutable. But if I understand this well enough, I think that we cover everything in an API that offers:

adding to the VFS
listing what's in the VFS
Initiating a garbage collection pass (you won't exactly have control over what gets cleared)

How does that sound?

**Comment by nick-thompson** [comment]
Ok great, so then let's use this issue for tracking the work to add:

* listing what's in the VFS
* Initiating a garbage collection pass (you won't exactly have control over what gets cleared)

I'll get that into the next release!

**Comment by cannc4** [comment]
> * listing what's in the VFS

Are you thinking of listing only the metadata or including the buffer too?

**Comment by cristianvogel** [comment]
I'm thinking that could be useful , for concatenation or downloading? 

I'm wary not to suggest too much mutability because perhaps that is not the intended scope of the VFS. 

Nevertheless, once we have gone to the trouble of Fetching (or user uploading) , decoding the ArrayBuffer to audio via the AudioContext , then naming and adding the separated channels to the VFS - being able to get the buffer back for editing or processing would save that whole process needing to be repeated.

**Comment by cristianvogel** [comment]
Yeah, that's a good solution. Thanks!

**Comment by nick-thompson** [comment]
Added in b94a08a2c6251806315f2ec338f814745e950446, this will roll out shortly in v2.1.0! 🎉
